big-o-notation-exercise - Jonathan Matsuda
jonathanymatsuda/c1021-code-solutions pull request #134
Opened 2022-01-10 23:43 UTC by jonathanymatsuda

![Screen Shot 2022-01-10 at 3 40 55 PM](https://user-images.githubusercontent.com/72685552/148856768-7ff13aca-a857-47cb-9791-b2e07009e318.png)

2022-01-10 23:47 UTC, thebearingedge requested changes

2022-01-10 23:47 UTC, thebearingedge commented on big-o-notation/big-o.js
> +      }
These actually happen up to `n * n` as well, since we're in a nested loop.

2022-01-10 23:47 UTC, thebearingedge commented on big-o-notation/big-o.js
> +    }
Everything inside of a loop is going to happen `n` times worst case.

2022-01-10 23:47 UTC, thebearingedge commented on big-o-notation/big-o.js
> +      let c = 0;                    // 1 * 1 = O(1)
This is inside of another loop, so it's actually `1 * n`

2022-01-11 00:14 UTC, jonathanymatsuda commented
![Screen Shot 2022-01-10 at 4 11 52 PM](https://user-images.githubusercontent.com/72685552/148859229-984e629d-d1cc-4066-9f29-46f282fcedf5.png)

2022-01-11 00:24 UTC, thebearingedge approved these changes

2022-01-12 18:44 UTC, merged